### ISSUE TITLE
System command error for several methods

### ISSUE THREAD

**Issue by cemalley** [dynverse/dynmethods#104]
Hi dynverse devs, wow! I am impressed with this project and the effort to make it easy to run many trajectory methods from the same prepared task. I have been testing dyno out with a scRNA dataset with 1385 cells and 13953 genes. I notice that several methods give a vague error:
`Error: Error during trajectory inference`
`System command error`

Methods that I tested and worked (finished the infer_trajectory):

- projected_slingshot
- scorpius
- projected_tscan
- embeddr
- waterfall

Methods that gave the system command error:

- projected_paga
- mclddr
- mclica
- recat (I was never able to get the source package to work either, agree with the low benchmark scores)
- slice
- ouija (but the author says it can only run on much smaller dimensions of data)

The one that really "hurts most" for not working is Monocle DDRTree. Could you provide at least more verbose errors for the failure? If you would like I can post the full code I'm running. The only parameter changing across the tests was method name.
Thank you, I know dyno is in active development.

**Comment by rcannood** [comment]
Hello @cemalley, 

Thanks for the nice words! 

The problem is due to the rapid iterations with which @zouter are still changing the code. The current version of dyno (and dynmethods and dynwrap) requires docker to be installed. Could you update dyno/dynwrap/dynmethods and install docker (if you haven't already)? 

If this does not yet solve your problem, could you set verbose to TRUE as to get insight into what the error might be?

mnclddr (and others) have recently been renamed to monocle_ddrtree, by the way.

Kind regards, 
Robrecht

**Comment by zouter** [comment]
Hi @cemalley 

Thanks for testing out the package. I hope it helps you with finding good trajectories in your data!

We made some large changes the last week which actually broke almost every docker container. Probably the dockers which worked for you were those which were downloaded after this change. We also pushed a fix today which fixed the paga wrapper for datasets over 500 cells.

So the most probable cause of the error is that the docker containers are out of sync. Could you try running `docker pull dynverse/monocle_ddrtree` in the command line (or, alternatively, run `dynwrap::pull_docker_ti_method("dynverse/monocle_ddrtree")` in R? And see whether you can then run Monocle DDRTree method on the dataset?

If you want more verbose input, you can set `verbose=TRUE` in `infer_trajectory`. We decided to put this off by default because most methods are very verbose by default. I'm working on a fix to return the output/error of the method when it errors.

Thanks!

Wouter

**Comment by rcannood** [comment]
@zouter and I just discussed this issue. We will make dynmethods automatically update dockers if an old version is being used. I'll keep you posted.

**Comment by zouter** [comment]
Hi @cemalley 

First, thank you for you patience. Your one of the first people using dyno for real use cases so there are some issues still in there..

For **Monocle**: Indeed, this is probably related to a memory issue. Indeed, when I run Monocle on a similarly sized dataset it also uses quite a bit of memory (at times 6GB). I had a look and this is probably due to differences in feature filtering. Our wrapper does not do any feature filtering (this wrapper was originally used for evaluating the methods, where for being fair for all methods we already filtered the genes prior to trajectory inference). I guess you did select some features for ordering as suggested in the tutorial?

In any case, I now updated all monocle wrappers to include feature filtering by default, using the one suggested in the monocle documentation:
```
  disp_table <- dispersionTable(cds)
  ordering_genes <- subset(disp_table, mean_expression >= params$filter_features_mean_expression)
  cds <- setOrderingFilter(cds, ordering_genes)
```

You can tune this using the parameters `filter_features` (logical) and `filter_features_mean_expression` (numeric).

For **PAGA**, this is an issue which we fixed recently with HDF5.


We recently made some updates to dynwrap and dynmethods to make sure the latest versions of the containers are always used. So I highly suggest updating dynmethods (dynwrap will also be updated): `devtools::install_github("dynverse/dynmethods")`. Then again running monocle or PAGA should automatically update the docker for you, and the errors should be fixed :crossed_fingers:

**Comment by cemalley** [comment]
Hi @zouter, I am up to date with the devel branch of dyno and dynmethods. I try both with cell_info and without in the task, but monocle still fails at the dimensionality reduction step. This is definitely the most intensive step in monocle. I was going to try to run this on NIH Biowulf with near-unlimited memory, but Docker is incompatible with the system. I made a markdown file of the local run, see this file I uploaded: http://htmlpreview.github.io/?https://github.com/cemalley/scRNASeq-bulkRNASeq/blob/master/dyno-example.htm I hope you can see the page. The data are a day 0 to 7 iPSC differentiation into neuroprogenitor cells, so the cell_info is day labeling. Thank you.

**Comment by rcannood** [comment]
Sorry, I lost track of this issue for a while. I'm not quite sure what the problem here is. Can you replicate the same problem on a different computer? Alternatively, you could remove the gene and cell names from your dataset and send it to us so we could have a look.

**Comment by cemalley** [comment]
Hi, I found Monocle DDRTree method failed for up to 8200 genes in the input dataset (constant 1385 cells). What is your email address?

**Comment by rcannood** [comment]
My email address is <mygithubhandle>@gmail.com :)

**Comment by rcannood** [comment]
Interestingly, that sortof matches [our results](https://raw.githubusercontent.com/dynverse/dynbenchmark_results/master/05-scaling/results/monocle_ddrtree.png) as well... only... transposed. On the left side, you can see a dataset sub- and super-sampled at various sizes. On a computer with 16GB of memory, it runs out of memory (orange) at around 10 features and ~9000 cells (bottom right), or at ~13000 features and 10 cells (top left)

**Comment by rcannood** [comment]
What. I'm a bit confused about what I wrote earlier. Before the 'at' symbol, I meant to write 'rcannood'. Just giving you the ending of an email address is a bit silly.

**Comment by cemalley** [comment]
Hi there, I don't think I can share my data at this time, but I will let you know if I get permission. Thank you. I am still watching the progress of this project and eagerly await any publication updates.

**Comment by zouter** [comment]
Closing this for now, but feel free to open a new issue if you still have issues!
